<?php if( !defined("SABIT") ){ exit; }
$hizmet["tr"] = "&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum ex eros, sit amet posuere diam pretium ut. Quisque rutrum ex dignissim, facilisis ligula non, tempor nisi. Praesent ut molestie ex. Nulla vitae urna sit amet metus lobortis ultrices vitae vel augue. Sed sit amet odio in nisi finibus dapibus. Aliquam erat volutpat. Etiam ultricies lacus nec mauris mattis rutrum. Mauris vestibulum dolor non lacus malesuada sodales. Integer ac eros diam. Suspendisse malesuada fermentum elit vitae pellentesque. Morbi vehicula ante vel lorem iaculis fermentum. Proin id est consectetur, luctus magna ut, dapibus eros. Nulla pretium rutrum nisi id venenatis.&lt;/p&gt;
&lt;p&gt;Integer sit amet neque vulputate, eleifend tortor et, fringilla tellus. Pellentesque eget augue in tellus porttitor tincidunt. Aenean vel felis in tortor elementum aliquam at in libero. Aenean tempus imperdiet dui, a viverra lacus aliquam non. Sed bibendum pharetra metus eu aliquam. Nullam id odio id augue blandit pretium eu in augue. Sed lectus mi, tempor sit amet augue nec, vulputate rhoncus turpis. Maecenas sagittis vulputate tellus sagittis facilisis. Phasellus laoreet arcu eget diam rutrum, vel sollicitudin neque tempor. Donec euismod sapien ac nunc posuere ultricies. Phasellus posuere malesuada iaculis. Vivamus in tristique ante. Donec pharetra, diam sed hendrerit efficitur, neque sem sodales est, lacinia aliquam libero arcu ac ante.&lt;/p&gt;
&lt;p&gt;Morbi sed orci tincidunt, condimentum turpis ut, pretium libero. In orci quam, eleifend sit amet scelerisque in, accumsan a urna. Mauris finibus dolor orci. Sed viverra vel odio in vestibulum. Vivamus elementum, tortor eu placerat fermentum, ligula erat venenatis erat, in auctor massa urna nec sem. Phasellus lobortis nulla vitae dolor fringilla iaculis. Nam venenatis non urna eu varius. Pellentesque eu ligula sed mauris lobortis facilisis. Nam pellentesque iaculis ipsum at mollis. Aliquam enim lectus, lobortis eu posuere vel, vehicula vitae metus. Morbi scelerisque feugiat mi, sed lobortis arcu blandit sit amet. Nam in erat vehicula, maximus leo eu, aliquam justo. Donec mollis sit amet turpis a faucibus. Donec et leo et nisi finibus sagittis.&lt;/p&gt;";
$girisyazi["tr"] = "&lt;p&gt;Hizmet Tr Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin hendrerit varius tortor sit amet congue. Sed porttitor ex ante, et maximus dolor tincidunt sit amet. Vivamus iaculis ac libero eu mattis. Integer porttitor sed magna non congue.&amp;nbsp;&lt;/p&gt;";
$hizmet["en"] = "&lt;p&gt;Lorem en ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum ex eros, sit amet posuere diam pretium ut. Quisque rutrum ex dignissim, facilisis ligula non, tempor nisi. Praesent ut molestie ex. Nulla vitae urna sit amet metus lobortis ultrices vitae vel augue. Sed sit amet odio in nisi finibus dapibus. Aliquam erat volutpat. Etiam ultricies lacus nec mauris mattis rutrum. Mauris vestibulum dolor non lacus malesuada sodales. Integer ac eros diam. Suspendisse malesuada fermentum elit vitae pellentesque. Morbi vehicula ante vel lorem iaculis fermentum. Proin id est consectetur, luctus magna ut, dapibus eros. Nulla pretium rutrum nisi id venenatis.&lt;/p&gt;
&lt;p&gt;Integer sit amet neque vulputate, eleifend tortor et, fringilla tellus. Pellentesque eget augue in tellus porttitor tincidunt. Aenean vel felis in tortor elementum aliquam at in libero. Aenean tempus imperdiet dui, a viverra lacus aliquam non. Sed bibendum pharetra metus eu aliquam. Nullam id odio id augue blandit pretium eu in augue. Sed lectus mi, tempor sit amet augue nec, vulputate rhoncus turpis. Maecenas sagittis vulputate tellus sagittis facilisis. Phasellus laoreet arcu eget diam rutrum, vel sollicitudin neque tempor. Donec euismod sapien ac nunc posuere ultricies. Phasellus posuere malesuada iaculis. Vivamus in tristique ante. Donec pharetra, diam sed hendrerit efficitur, neque sem sodales est, lacinia aliquam libero arcu ac ante.&lt;/p&gt;
&lt;p&gt;Morbi sed orci tincidunt, condimentum turpis ut, pretium libero. In orci quam, eleifend sit amet scelerisque in, accumsan a urna. Mauris finibus dolor orci. Sed viverra vel odio in vestibulum. Vivamus elementum, tortor eu placerat fermentum, ligula erat venenatis erat, in auctor massa urna nec sem. Phasellus lobortis nulla vitae dolor fringilla iaculis. Nam venenatis non urna eu varius. Pellentesque eu ligula sed mauris lobortis facilisis. Nam pellentesque iaculis ipsum at mollis. Aliquam enim lectus, lobortis eu posuere vel, vehicula vitae metus. Morbi scelerisque feugiat mi, sed lobortis arcu blandit sit amet. Nam in erat vehicula, maximus leo eu, aliquam justo. Donec mollis sit amet turpis a faucibus. Donec et leo et nisi finibus sagittis.&lt;/p&gt;";
$girisyazi["en"] = "&lt;p&gt;Hizmet Tr Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin hendrerit varius tortor sit amet congue. Sed porttitor ex ante, et maximus dolor tincidunt sit amet. Vivamus iaculis ac libero eu mattis. Integer porttitor sed magna non congue.&amp;nbsp;&lt;/p&gt;";

?>