<?php if( !defined("SABIT") ){ exit; }

$satissozlesme = "&lt;p&gt;&lt;strong&gt;TARAFLAR&amp;nbsp;MADDE 1-&amp;nbsp;SATICI/SAĞLAYICI: ğğğşşş&lt;/strong&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td width=&quot;150&quot;&gt;
&lt;p&gt;&lt;strong&gt;Unvanı:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;Safir Bitkisel &amp;Uuml;r&amp;uuml;nler Kırtasiye Giyim Temizlik REklam ve Organizasyon Sanayi ve Ticaret Limited Şirketi&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Adresi:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;ArifiyeMah. Semt Tanış Sok..No:14 D:5 Odunpazarı / ESKİŞEHİR&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Telefon:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;E-mail:&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;destek@saklicekmecem.com&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;M&amp;Uuml;ŞTERİ:&lt;/p&gt;
&lt;p&gt;Adı-Soyadı/&amp;Uuml;nvanı: {%ALICI_ADISOYAD%}&lt;br /&gt; Adresi:&amp;nbsp;{%ALICI_ADRES%}&lt;br /&gt; Telefon: {%ALICI_TELEFON%}&lt;br /&gt; E-mail: {%ALICI_EMAIL%}&lt;br /&gt; (bundan b&amp;ouml;yle &amp;Uuml;YE olarak anılacaktır)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 2- S&amp;Ouml;ZLEŞMENİN KONUSU&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;İşbu s&amp;ouml;zleşmenin konusu, Alıcının Satıcıya ait www.saklicekmecem.com web sitesinden elektronik ortamda sipariş verdiği, s&amp;ouml;zleşmede bahsi ge&amp;ccedil;en nitelikleri haiz ve yine s&amp;ouml;zleşmede satış fiyatı belirtilen mal/hizmetin satışı ve teslimi ile ilgili olarak 4077 sayılı T&amp;uuml;keticilerin Korunması Hakkındaki Kanun ve Mesafeli S&amp;ouml;zleşmeler Uygulama Esas ve Usulleri Hakkında Y&amp;ouml;netmelik h&amp;uuml;k&amp;uuml;mleri gereğince tarafların hak ve y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;klerinin saptanmasıdır. Alıcı, satışa konu mal/hizmetlerin temel nitelikleri, satış fiyatı, &amp;ouml;deme şekli, teslimat koşulları vs. satışa konu mal/hizmet ile ilgili t&amp;uuml;m &amp;ouml;n bilgiler ve cayma hakkı konusunda bilgi sahibi olduğunu, bu &amp;ouml;n bilgileri elektronik ortamda teyit ettiğini ve sonrasında mal/hizmeti sipariş verdiğini iş bu s&amp;ouml;zleşme h&amp;uuml;k&amp;uuml;mlerince kabul ve beyan eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 3- GENEL H&amp;Uuml;K&amp;Uuml;MLER&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.1.Alıcı, www.saklicekmecem.com internet sitesinde s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n temel nitelikleri, t&amp;uuml;m vergiler dahil satış fiyatı ve &amp;ouml;deme şekli ile teslimata ve bunun masraflarının alıcı tarafından karşılanacağına, teslimatın ger&amp;ccedil;ekleştirileceği s&amp;uuml;reye ve satıcının tam ticari unvanı, a&amp;ccedil;ık adresi ve iletişim bilgilerine ilişkin &amp;ouml;n bilgileri okuyup bilgi sahibi olduğunu ve elektronik ortamda gerekli teyidi verdiğini beyan eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.2. Alıcı; bu s&amp;ouml;zleşmeyi elektronik ortamda teyit etmekle, mesafeli s&amp;ouml;zleşmelerin akdinden &amp;ouml;nce, satıcı tarafından t&amp;uuml;keticiye verilmesi gereken adres, siparişi verilen &amp;uuml;r&amp;uuml;nlere ait temel &amp;ouml;zellikler, &amp;uuml;r&amp;uuml;nlerin vergiler dahil fiyatı, &amp;ouml;deme ve teslimat bilgilerini de doğru ve eksiksiz olarak edindiğini teyid etmiş olur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.3. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n, yasal 30 g&amp;uuml;nl&amp;uuml;k s&amp;uuml;reyi aşmamak koşulu ile her bir &amp;uuml;r&amp;uuml;n i&amp;ccedil;in alıcının yerleşim yerinin uzaklığına bağlı olarak internet sitesinde &amp;ouml;n bilgiler i&amp;ccedil;inde a&amp;ccedil;ıklanan s&amp;uuml;re i&amp;ccedil;inde alıcı veya g&amp;ouml;sterdiği adresteki kişi/kuruluşa teslim edilir. Kargo ve Teslimat bilgileri kısmında g&amp;ouml;sterilen teslimata ilişkin her t&amp;uuml;rl&amp;uuml; kargo &amp;uuml;creti alıcı tarafından karşılanacak olup siparişine ilişkin faturasına &#39;&#39;Kargo &amp;Uuml;creti&#39;&#39; adı altında yansıtılacaktır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.4. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n, alıcıdan başka bir kişi/kuruluşa teslim edilecek ise, teslim edilecek kişi/kuruluşun teslimatı kabul etmemesinden satıcı sorumlu tutulamaz.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.5. Kargo firmasının, &amp;uuml;r&amp;uuml;n&amp;uuml; alıcıya teslimi aşamasında karşılaşacağı her t&amp;uuml;rl&amp;uuml; sorun nedeniyle, siparişi verilen &amp;uuml;r&amp;uuml;n&amp;uuml;n alıcıya teslim edilememesinden dolayı satıcı sorumlu tutulamaz.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.6. Satıcı, s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n sağlam, eksiksiz, siparişte belirtilen niteliklere uygun ve varsa garanti belgeleri ve kullanım kılavuzları ile teslim edilmesinden sorumludur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.7. Satıcı, haklı bir sebebe dayanmak şartıyla, s&amp;ouml;zleşmeden doğan ifa y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;n&amp;uuml;n s&amp;uuml;resi dolmadan alıcıya eşit kalite ve fiyatta farklı bir &amp;uuml;r&amp;uuml;n tedarik edebilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.8. Satıcı, sipariş konusu &amp;uuml;r&amp;uuml;n veya hizmetin yerine getirilmesinin imkansızlaşması halinde s&amp;ouml;zleşme konusu y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;klerini yerine getiremezse, bu durumu, s&amp;ouml;zleşmeden doğan ifa y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;n&amp;uuml;n s&amp;uuml;resi dolmadan t&amp;uuml;keticiye bildirir ve alıcıya eşit kalite ve fiyatta farklı bir &amp;uuml;r&amp;uuml;n tedarik edebilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.9. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n teslimatı i&amp;ccedil;in işbu s&amp;ouml;zleşmenin online ortamda kabul edilerek satıcıya ulaştırılmış olması ve bedelinin alıcının tercih ettiği &amp;ouml;deme şekli ile &amp;ouml;denmiş olması şarttır. Herhangi bir nedenle &amp;uuml;r&amp;uuml;n bedeli &amp;ouml;denmez veya banka kayıtlarında iptal edilir ise, satıcı &amp;uuml;r&amp;uuml;n&amp;uuml;n teslimi y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;nden kurtulmuş kabul edilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.10. &amp;Uuml;r&amp;uuml;n&amp;uuml;n tesliminden sonra alıcıya ait kredi kartının alıcının kusurundan kaynaklanmayan bir şekilde yetkisiz kişilerce haksız veya hukuka aykırı olarak kullanılması nedeni ile ilgili banka veya finans kuruluşun &amp;uuml;r&amp;uuml;n bedelini satıcıya &amp;ouml;dememesi halinde, alıcının kendisine teslim edilmiş olması kaydıyla &amp;uuml;r&amp;uuml;n&amp;uuml;n 3 g&amp;uuml;n i&amp;ccedil;inde satıcıya g&amp;ouml;nderilmesi zorunludur. Bu takdirde nakliye giderleri alıcıya aittir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.11. Satıcı m&amp;uuml;cbir sebepler veya nakliyeyi engelleyen hava muhalefeti, ulaşımın kesilmesi gibi olağan&amp;uuml;st&amp;uuml; durumlar nedeni ile s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml; s&amp;uuml;resi i&amp;ccedil;inde teslim edemez ise, durumu alıcıya bildirmekle y&amp;uuml;k&amp;uuml;ml&amp;uuml;d&amp;uuml;r. Bu takdirde alıcı siparişin iptal edilmesini, s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n varsa emsali ile değiştirilmesini, ve/veya teslimat s&amp;uuml;resinin engelleyici durumun ortadan kalkmasına kadar ertelenmesi haklarından birini kullanabilir. Alıcının siparişi iptal etmesi halinde &amp;ouml;dediği tutar 14 g&amp;uuml;n i&amp;ccedil;inde kendisine &amp;ouml;denir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcnın kredi kartı ile yaptığı &amp;ouml;demelerde ise, &amp;uuml;r&amp;uuml;n tutarı, siparişin alıcı tarafından iptal edilmesinden sonra 14 g&amp;uuml;n i&amp;ccedil;erisinde ilgili bankaya iade edilir. Bu tutarın bankaya iadesinden sonra alıcı hesaplarına yansıması tamamen banka işlem s&amp;uuml;reci ile ilgili olduğundan, alıcı, olası gecikmeler i&amp;ccedil;in satıcının herhangi bir şekilde m&amp;uuml;dahalede bulunmasının m&amp;uuml;mk&amp;uuml;n olamayacağını ve satıcı tarafından kredi kartına iade edilen tutarın banka tarafından alıcı hesabına yansıtılmasının ortalama 2 ile 3 haftayı bulabileceğini şimdiden kabul etmektedir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 4- TESLİMAT MASRAFLARI VE İFASI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Teslimat masrafları alıcıya aittir. Satıcı, web sitesinde, ilan ettiği rakamın &amp;uuml;zerinde alışveriş yapanların teslimat &amp;uuml;cretinin kendisince karşılanacağını beyan ettiği durumlarda, teslimat masrafı satıcıya aittir. Teslimat; stokun m&amp;uuml;sait olması ve mal bedelinin satıcının hesabına ge&amp;ccedil;mesinden sonra en kısa s&amp;uuml;rede yapılır. Satıcı, mal/hizmetin siparişinden itibaren 30 (Otuz) g&amp;uuml;n i&amp;ccedil;erisinde teslim eder. Herhangi bir nedenle mal/hizmet bedeli &amp;ouml;denmez veya banka kayıtlarında iptal edilir ise, Satıcı mal/hizmetin teslimi y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;nden kurtulmuş kabul edilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 5- S&amp;Ouml;ZLEŞMEYE KONU MAL/HİZMETİN &amp;Ouml;ZELLİKLERİ&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin cinsi ve t&amp;uuml;r&amp;uuml;, miktarı, marka/modeli, rengi ve t&amp;uuml;m vergiler d&amp;acirc;hil satış bedeli www.saklicekmecem.com adlı web sitesindeki mal/hizmet tanıtım sayfasında yer alan bilgilerde ve iş bu s&amp;ouml;zleşmenin ayrılmaz par&amp;ccedil;ası sayılan faturada belirtildiği gibidir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 6- MAL/HİZMETİN PEŞİN FİYATI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin peşin fiyatı sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 7- VADELİ FİYAT&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin satış fiyatına yapılan vadeye g&amp;ouml;re fiyatı&amp;nbsp;sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 8- FAİZ&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin satış fiyatına yapılan vadeye g&amp;ouml;re fiyatı&amp;nbsp;sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 9- CAYMA HAKKI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcı, s&amp;ouml;zleşme konusu mal/hizmetin kendisine veya g&amp;ouml;sterdiği adresteki kişi/kuruluşa tesliminden itibaren 14(ond&amp;ouml;rt) g&amp;uuml;n i&amp;ccedil;inde cayma hakkını kullanabilir. Cayma hakkının kullanılması i&amp;ccedil;in aynı s&amp;uuml;re i&amp;ccedil;inde satıcıya e-posta ile bildirimde bulunulması ve mal/hizmetin 15. md. h&amp;uuml;k&amp;uuml;mleri &amp;ccedil;er&amp;ccedil;evesinde ve işbu s&amp;ouml;zleşmenin ayrılmaz par&amp;ccedil;ası olan ve www.saklicekmecem.com web sitesinde yayınlanmış olan &amp;ouml;n bilgiler gereğince, kullanılmamış ve paketinin hasar g&amp;ouml;rmemiş ayrıca i&amp;ccedil; giyim &amp;uuml;r&amp;uuml;nlerinde ambalajının a&amp;ccedil;ılmamış olması şarttır. Bu hakkın kullanılması halinde, 3. kişiye veya alıcıya teslim edilen mal/hizmete ilişkin fatura aslının iadesi zorunludur. Cayma hakkına ilişkin ihbarın ulaşmasını takip eden 14 g&amp;uuml;n i&amp;ccedil;inde mal/hizmet bedeli alıcıya iade edilir ve 20 (yirmi) g&amp;uuml;nl&amp;uuml;k s&amp;uuml;re i&amp;ccedil;inde mal/hizmet iade alınır. Fatura aslı g&amp;ouml;nderilmezse alıcıya KDV ve varsa diğer yasal y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;kler iade edilemez. Cayma hakkı nedeni ile iade edilen mal/hizmetin teslimat bedeli satıcı tarafından karşılanır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 10- CAYMA HAKKI KULLANILAMAYACAK MAL/HİZMETLER&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Niteliği itibarıyla iade edilemeyecek mal/hizmetler, hızla bozulan ve son kullanma tarihi ge&amp;ccedil;en mal/hizmetler, tek kullanımlık mal/hizmetler, hijyen kuralları gerektiren &amp;uuml;r&amp;uuml;nlerdir. Ayrıca, her t&amp;uuml;rl&amp;uuml; giyim, sağlık ve kozmetik malzemelerinde cayma hakkının kullanılabilmesi i&amp;ccedil;in mal/hizmetin ambalajının a&amp;ccedil;ılmamış, bozulmamış ve kullanılmamış olmaları şartı bulunmaktadır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Teslimatta &amp;Ouml;deme metoduyla yapılan alış verişlerde, sipariş kargoya verildikten sonra cayma hakkı kullanılması durumunda, satıcının web sitesinde beyan ettiği miktarlardaki gidiş-d&amp;ouml;n&amp;uuml;ş kargo masrafları ile gidiş-d&amp;ouml;n&amp;uuml;ş tahsilatlı g&amp;ouml;nderi komisyon masrafları alıcı tarafından karşılanır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 11- TEMERR&amp;Uuml;D HALİ VE HUKUKİ SONU&amp;Ccedil;LARI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcı kredi kartı ile yapmış olduğu işlemlerinde temerr&amp;uuml;de d&amp;uuml;şmesi halinde kart sahibi bankanın kendisi ile yapmış olduğu kredi kartı s&amp;ouml;zleşmesi &amp;ccedil;er&amp;ccedil;evesinde faiz &amp;ouml;deyecek ve bankaya karsı sorumlu olacaktır. Bu durumda ilgili banka hukuki yollara başvurabilir; doğacak masrafları ve vek&amp;acirc;let &amp;uuml;cretini Alıcıdan talep edebilir ve her koşulda alıcının borcundan dolayı temerr&amp;uuml;de d&amp;uuml;şmesi halinde, alıcı, borcun gecikmeli ifasından dolayı satıcının oluşan zarar ve ziyanını &amp;ouml;demeyi kabul eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 12-&amp;nbsp;YETKİLİ MAHKEME&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;İşbu s&amp;ouml;zleşmeden kaynaklanabilecek ihtilaflarda, Sanayi ve Ticaret Bakanlığınca ilan edilen değere kadar T&amp;uuml;ketici Hakem Heyetleri t&amp;uuml;ketici mahkemesi bulunamayan yerlerde Asliye Hukuk Mahkemeleri yetkilidir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Siparişin ger&amp;ccedil;ekleşmesi durumunda ALICI işbu s&amp;ouml;zleşmenin t&amp;uuml;m koşullarını kabul etmiş sayılır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;SATICI/SAĞLAYICI :&amp;nbsp;Safir Bitkisel &amp;Uuml;r&amp;uuml;nler Kırtasiye Giyim Temizlik REklam ve Organizasyon Sanayi ve Ticaret Limited Şirketi&lt;br /&gt; ALICI :&amp;nbsp;{%ALICI_ADISOYAD%}&lt;/p&gt;";
$onsozlesme    = "&lt;p&gt;&lt;strong&gt;TARAFLAR&amp;nbsp;MADDE 1-&amp;nbsp;SATICI/SAĞLAYICI:&lt;/strong&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td width=&quot;150&quot;&gt;
&lt;p&gt;&lt;strong&gt;Unvanı:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;Safir Bitkisel &amp;Uuml;r&amp;uuml;nler Kırtasiye Giyim Temizlik REklam ve Organizasyon Sanayi ve Ticaret Limited Şirketi&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Adresi:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;ArifiyeMah. Semt Tanış Sok..No:14 D:5 Odunpazarı / ESKİŞEHİR&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Telefon:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;E-mail:&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;destek@saklicekmecem.com&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;M&amp;Uuml;ŞTERİ:&lt;/p&gt;
&lt;p&gt;Adı-Soyadı/&amp;Uuml;nvanı: {%ALICI_ADISOYAD%}&lt;br /&gt;Adresi:&amp;nbsp;{%ALICI_ADRES%}&lt;br /&gt;Telefon: {%ALICI_TELEFON%}&lt;br /&gt;E-mail: {%ALICI_EMAIL%}&lt;br /&gt;(bundan b&amp;ouml;yle &amp;Uuml;YE olarak anılacaktır)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 2- S&amp;Ouml;ZLEŞMENİN KONUSU&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;İşbu s&amp;ouml;zleşmenin konusu, Alıcının Satıcıya ait www.saklicekmecem.com web sitesinden elektronik ortamda sipariş verdiği, s&amp;ouml;zleşmede bahsi ge&amp;ccedil;en nitelikleri haiz ve yine s&amp;ouml;zleşmede satış fiyatı belirtilen mal/hizmetin satışı ve teslimi ile ilgili olarak 4077 sayılı T&amp;uuml;keticilerin Korunması Hakkındaki Kanun ve Mesafeli S&amp;ouml;zleşmeler Uygulama Esas ve Usulleri Hakkında Y&amp;ouml;netmelik h&amp;uuml;k&amp;uuml;mleri gereğince tarafların hak ve y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;klerinin saptanmasıdır. Alıcı, satışa konu mal/hizmetlerin temel nitelikleri, satış fiyatı, &amp;ouml;deme şekli, teslimat koşulları vs. satışa konu mal/hizmet ile ilgili t&amp;uuml;m &amp;ouml;n bilgiler ve cayma hakkı konusunda bilgi sahibi olduğunu, bu &amp;ouml;n bilgileri elektronik ortamda teyit ettiğini ve sonrasında mal/hizmeti sipariş verdiğini iş bu s&amp;ouml;zleşme h&amp;uuml;k&amp;uuml;mlerince kabul ve beyan eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 3- GENEL H&amp;Uuml;K&amp;Uuml;MLER&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.1.Alıcı, www.saklicekmecem.com internet sitesinde s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n temel nitelikleri, t&amp;uuml;m vergiler dahil satış fiyatı ve &amp;ouml;deme şekli ile teslimata ve bunun masraflarının alıcı tarafından karşılanacağına, teslimatın ger&amp;ccedil;ekleştirileceği s&amp;uuml;reye ve satıcının tam ticari unvanı, a&amp;ccedil;ık adresi ve iletişim bilgilerine ilişkin &amp;ouml;n bilgileri okuyup bilgi sahibi olduğunu ve elektronik ortamda gerekli teyidi verdiğini beyan eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.2. Alıcı; bu s&amp;ouml;zleşmeyi elektronik ortamda teyit etmekle, mesafeli s&amp;ouml;zleşmelerin akdinden &amp;ouml;nce, satıcı tarafından t&amp;uuml;keticiye verilmesi gereken adres, siparişi verilen &amp;uuml;r&amp;uuml;nlere ait temel &amp;ouml;zellikler, &amp;uuml;r&amp;uuml;nlerin vergiler dahil fiyatı, &amp;ouml;deme ve teslimat bilgilerini de doğru ve eksiksiz olarak edindiğini teyid etmiş olur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.3. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n, yasal 30 g&amp;uuml;nl&amp;uuml;k s&amp;uuml;reyi aşmamak koşulu ile her bir &amp;uuml;r&amp;uuml;n i&amp;ccedil;in alıcının yerleşim yerinin uzaklığına bağlı olarak internet sitesinde &amp;ouml;n bilgiler i&amp;ccedil;inde a&amp;ccedil;ıklanan s&amp;uuml;re i&amp;ccedil;inde alıcı veya g&amp;ouml;sterdiği adresteki kişi/kuruluşa teslim edilir. Kargo ve Teslimat bilgileri kısmında g&amp;ouml;sterilen teslimata ilişkin her t&amp;uuml;rl&amp;uuml; kargo &amp;uuml;creti alıcı tarafından karşılanacak olup siparişine ilişkin faturasına &#39;&#39;Kargo &amp;Uuml;creti&#39;&#39; adı altında yansıtılacaktır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.4. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n, alıcıdan başka bir kişi/kuruluşa teslim edilecek ise, teslim edilecek kişi/kuruluşun teslimatı kabul etmemesinden satıcı sorumlu tutulamaz.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.5. Kargo firmasının, &amp;uuml;r&amp;uuml;n&amp;uuml; alıcıya teslimi aşamasında karşılaşacağı her t&amp;uuml;rl&amp;uuml; sorun nedeniyle, siparişi verilen &amp;uuml;r&amp;uuml;n&amp;uuml;n alıcıya teslim edilememesinden dolayı satıcı sorumlu tutulamaz.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.6. Satıcı, s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n sağlam, eksiksiz, siparişte belirtilen niteliklere uygun ve varsa garanti belgeleri ve kullanım kılavuzları ile teslim edilmesinden sorumludur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.7. Satıcı, haklı bir sebebe dayanmak şartıyla, s&amp;ouml;zleşmeden doğan ifa y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;n&amp;uuml;n s&amp;uuml;resi dolmadan alıcıya eşit kalite ve fiyatta farklı bir &amp;uuml;r&amp;uuml;n tedarik edebilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.8. Satıcı, sipariş konusu &amp;uuml;r&amp;uuml;n veya hizmetin yerine getirilmesinin imkansızlaşması halinde s&amp;ouml;zleşme konusu y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;klerini yerine getiremezse, bu durumu, s&amp;ouml;zleşmeden doğan ifa y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;n&amp;uuml;n s&amp;uuml;resi dolmadan t&amp;uuml;keticiye bildirir ve alıcıya eşit kalite ve fiyatta farklı bir &amp;uuml;r&amp;uuml;n tedarik edebilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.9. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n teslimatı i&amp;ccedil;in işbu s&amp;ouml;zleşmenin online ortamda kabul edilerek satıcıya ulaştırılmış olması ve bedelinin alıcının tercih ettiği &amp;ouml;deme şekli ile &amp;ouml;denmiş olması şarttır. Herhangi bir nedenle &amp;uuml;r&amp;uuml;n bedeli &amp;ouml;denmez veya banka kayıtlarında iptal edilir ise, satıcı &amp;uuml;r&amp;uuml;n&amp;uuml;n teslimi y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;nden kurtulmuş kabul edilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.10. &amp;Uuml;r&amp;uuml;n&amp;uuml;n tesliminden sonra alıcıya ait kredi kartının alıcının kusurundan kaynaklanmayan bir şekilde yetkisiz kişilerce haksız veya hukuka aykırı olarak kullanılması nedeni ile ilgili banka veya finans kuruluşun &amp;uuml;r&amp;uuml;n bedelini satıcıya &amp;ouml;dememesi halinde, alıcının kendisine teslim edilmiş olması kaydıyla &amp;uuml;r&amp;uuml;n&amp;uuml;n 3 g&amp;uuml;n i&amp;ccedil;inde satıcıya g&amp;ouml;nderilmesi zorunludur. Bu takdirde nakliye giderleri alıcıya aittir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.11. Satıcı m&amp;uuml;cbir sebepler veya nakliyeyi engelleyen hava muhalefeti, ulaşımın kesilmesi gibi olağan&amp;uuml;st&amp;uuml; durumlar nedeni ile s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml; s&amp;uuml;resi i&amp;ccedil;inde teslim edemez ise, durumu alıcıya bildirmekle y&amp;uuml;k&amp;uuml;ml&amp;uuml;d&amp;uuml;r. Bu takdirde alıcı siparişin iptal edilmesini, s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n varsa emsali ile değiştirilmesini, ve/veya teslimat s&amp;uuml;resinin engelleyici durumun ortadan kalkmasına kadar ertelenmesi haklarından birini kullanabilir. Alıcının siparişi iptal etmesi halinde &amp;ouml;dediği tutar 14 g&amp;uuml;n i&amp;ccedil;inde kendisine &amp;ouml;denir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcnın kredi kartı ile yaptığı &amp;ouml;demelerde ise, &amp;uuml;r&amp;uuml;n tutarı, siparişin alıcı tarafından iptal edilmesinden sonra 14 g&amp;uuml;n i&amp;ccedil;erisinde ilgili bankaya iade edilir. Bu tutarın bankaya iadesinden sonra alıcı hesaplarına yansıması tamamen banka işlem s&amp;uuml;reci ile ilgili olduğundan, alıcı, olası gecikmeler i&amp;ccedil;in satıcının herhangi bir şekilde m&amp;uuml;dahalede bulunmasının m&amp;uuml;mk&amp;uuml;n olamayacağını ve satıcı tarafından kredi kartına iade edilen tutarın banka tarafından alıcı hesabına yansıtılmasının ortalama 2 ile 3 haftayı bulabileceğini şimdiden kabul etmektedir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 4- TESLİMAT MASRAFLARI VE İFASI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Teslimat masrafları alıcıya aittir. Satıcı, web sitesinde, ilan ettiği rakamın &amp;uuml;zerinde alışveriş yapanların teslimat &amp;uuml;cretinin kendisince karşılanacağını beyan ettiği durumlarda, teslimat masrafı satıcıya aittir. Teslimat; stokun m&amp;uuml;sait olması ve mal bedelinin satıcının hesabına ge&amp;ccedil;mesinden sonra en kısa s&amp;uuml;rede yapılır. Satıcı, mal/hizmetin siparişinden itibaren 30 (Otuz) g&amp;uuml;n i&amp;ccedil;erisinde teslim eder. Herhangi bir nedenle mal/hizmet bedeli &amp;ouml;denmez veya banka kayıtlarında iptal edilir ise, Satıcı mal/hizmetin teslimi y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;nden kurtulmuş kabul edilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 5- S&amp;Ouml;ZLEŞMEYE KONU MAL/HİZMETİN &amp;Ouml;ZELLİKLERİ&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin cinsi ve t&amp;uuml;r&amp;uuml;, miktarı, marka/modeli, rengi ve t&amp;uuml;m vergiler d&amp;acirc;hil satış bedeli www.saklicekmecem.com adlı web sitesindeki mal/hizmet tanıtım sayfasında yer alan bilgilerde ve iş bu s&amp;ouml;zleşmenin ayrılmaz par&amp;ccedil;ası sayılan faturada belirtildiği gibidir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 6- MAL/HİZMETİN PEŞİN FİYATI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin peşin fiyatı sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 7- VADELİ FİYAT&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin satış fiyatına yapılan vadeye g&amp;ouml;re fiyatı&amp;nbsp;sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 8- FAİZ&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin satış fiyatına yapılan vadeye g&amp;ouml;re fiyatı&amp;nbsp;sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 9- CAYMA HAKKI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcı, s&amp;ouml;zleşme konusu mal/hizmetin kendisine veya g&amp;ouml;sterdiği adresteki kişi/kuruluşa tesliminden itibaren 14(ond&amp;ouml;rt) g&amp;uuml;n i&amp;ccedil;inde cayma hakkını kullanabilir. Cayma hakkının kullanılması i&amp;ccedil;in aynı s&amp;uuml;re i&amp;ccedil;inde satıcıya e-posta ile bildirimde bulunulması ve mal/hizmetin 15. md. h&amp;uuml;k&amp;uuml;mleri &amp;ccedil;er&amp;ccedil;evesinde ve işbu s&amp;ouml;zleşmenin ayrılmaz par&amp;ccedil;ası olan ve www.saklicekmecem.com web sitesinde yayınlanmış olan &amp;ouml;n bilgiler gereğince, kullanılmamış ve paketinin hasar g&amp;ouml;rmemiş ayrıca i&amp;ccedil; giyim &amp;uuml;r&amp;uuml;nlerinde ambalajının a&amp;ccedil;ılmamış olması şarttır. Bu hakkın kullanılması halinde, 3. kişiye veya alıcıya teslim edilen mal/hizmete ilişkin fatura aslının iadesi zorunludur. Cayma hakkına ilişkin ihbarın ulaşmasını takip eden 14 g&amp;uuml;n i&amp;ccedil;inde mal/hizmet bedeli alıcıya iade edilir ve 20 (yirmi) g&amp;uuml;nl&amp;uuml;k s&amp;uuml;re i&amp;ccedil;inde mal/hizmet iade alınır. Fatura aslı g&amp;ouml;nderilmezse alıcıya KDV ve varsa diğer yasal y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;kler iade edilemez. Cayma hakkı nedeni ile iade edilen mal/hizmetin teslimat bedeli satıcı tarafından karşılanır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 10- CAYMA HAKKI KULLANILAMAYACAK MAL/HİZMETLER&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Niteliği itibarıyla iade edilemeyecek mal/hizmetler, hızla bozulan ve son kullanma tarihi ge&amp;ccedil;en mal/hizmetler, tek kullanımlık mal/hizmetler, hijyen kuralları gerektiren &amp;uuml;r&amp;uuml;nlerdir. Ayrıca, her t&amp;uuml;rl&amp;uuml; giyim, sağlık ve kozmetik malzemelerinde cayma hakkının kullanılabilmesi i&amp;ccedil;in mal/hizmetin ambalajının a&amp;ccedil;ılmamış, bozulmamış ve kullanılmamış olmaları şartı bulunmaktadır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Teslimatta &amp;Ouml;deme metoduyla yapılan alış verişlerde, sipariş kargoya verildikten sonra cayma hakkı kullanılması durumunda, satıcının web sitesinde beyan ettiği miktarlardaki gidiş-d&amp;ouml;n&amp;uuml;ş kargo masrafları ile gidiş-d&amp;ouml;n&amp;uuml;ş tahsilatlı g&amp;ouml;nderi komisyon masrafları alıcı tarafından karşılanır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 11- TEMERR&amp;Uuml;D HALİ VE HUKUKİ SONU&amp;Ccedil;LARI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcı kredi kartı ile yapmış olduğu işlemlerinde temerr&amp;uuml;de d&amp;uuml;şmesi halinde kart sahibi bankanın kendisi ile yapmış olduğu kredi kartı s&amp;ouml;zleşmesi &amp;ccedil;er&amp;ccedil;evesinde faiz &amp;ouml;deyecek ve bankaya karsı sorumlu olacaktır. Bu durumda ilgili banka hukuki yollara başvurabilir; doğacak masrafları ve vek&amp;acirc;let &amp;uuml;cretini Alıcıdan talep edebilir ve her koşulda alıcının borcundan dolayı temerr&amp;uuml;de d&amp;uuml;şmesi halinde, alıcı, borcun gecikmeli ifasından dolayı satıcının oluşan zarar ve ziyanını &amp;ouml;demeyi kabul eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 12-&amp;nbsp;YETKİLİ MAHKEME&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;İşbu s&amp;ouml;zleşmeden kaynaklanabilecek ihtilaflarda, Sanayi ve Ticaret Bakanlığınca ilan edilen değere kadar T&amp;uuml;ketici Hakem Heyetleri t&amp;uuml;ketici mahkemesi bulunamayan yerlerde Asliye Hukuk Mahkemeleri yetkilidir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Siparişin ger&amp;ccedil;ekleşmesi durumunda ALICI işbu s&amp;ouml;zleşmenin t&amp;uuml;m koşullarını kabul etmiş sayılır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;SATICI/SAĞLAYICI :&amp;nbsp;Safir Bitkisel &amp;Uuml;r&amp;uuml;nler Kırtasiye Giyim Temizlik REklam ve Organizasyon Sanayi ve Ticaret Limited Şirketi&lt;br /&gt;ALICI :&amp;nbsp;{%ALICI_ADISOYAD%}&lt;/p&gt;";
$usersozlesme  = "&lt;p&gt;&lt;strong&gt;TARAFLAR&amp;nbsp;MADDE 1-&amp;nbsp;SATICI/SAĞLAYICI:&lt;/strong&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td width=&quot;150&quot;&gt;
&lt;p&gt;&lt;strong&gt;Unvanı:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;Safir Bitkisel &amp;Uuml;r&amp;uuml;nler Kırtasiye Giyim Temizlik REklam ve Organizasyon Sanayi ve Ticaret Limited Şirketi&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Adresi:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;ArifiyeMah. Semt Tanış Sok..No:14 D:5 Odunpazarı / ESKİŞEHİR&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Telefon:&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;E-mail:&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;destek@saklicekmecem.com&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;M&amp;Uuml;ŞTERİ:&lt;/p&gt;
&lt;p&gt;Adı-Soyadı/&amp;Uuml;nvanı: {%ALICI_ADISOYAD%}&lt;br /&gt;Adresi:&amp;nbsp;{%ALICI_ADRES%}&lt;br /&gt;Telefon: {%ALICI_TELEFON%}&lt;br /&gt;E-mail: {%ALICI_EMAIL%}&lt;br /&gt;(bundan b&amp;ouml;yle &amp;Uuml;YE olarak anılacaktır)&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 2- S&amp;Ouml;ZLEŞMENİN KONUSU&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;İşbu s&amp;ouml;zleşmenin konusu, Alıcının Satıcıya ait www.saklicekmecem.com web sitesinden elektronik ortamda sipariş verdiği, s&amp;ouml;zleşmede bahsi ge&amp;ccedil;en nitelikleri haiz ve yine s&amp;ouml;zleşmede satış fiyatı belirtilen mal/hizmetin satışı ve teslimi ile ilgili olarak 4077 sayılı T&amp;uuml;keticilerin Korunması Hakkındaki Kanun ve Mesafeli S&amp;ouml;zleşmeler Uygulama Esas ve Usulleri Hakkında Y&amp;ouml;netmelik h&amp;uuml;k&amp;uuml;mleri gereğince tarafların hak ve y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;klerinin saptanmasıdır. Alıcı, satışa konu mal/hizmetlerin temel nitelikleri, satış fiyatı, &amp;ouml;deme şekli, teslimat koşulları vs. satışa konu mal/hizmet ile ilgili t&amp;uuml;m &amp;ouml;n bilgiler ve cayma hakkı konusunda bilgi sahibi olduğunu, bu &amp;ouml;n bilgileri elektronik ortamda teyit ettiğini ve sonrasında mal/hizmeti sipariş verdiğini iş bu s&amp;ouml;zleşme h&amp;uuml;k&amp;uuml;mlerince kabul ve beyan eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 3- GENEL H&amp;Uuml;K&amp;Uuml;MLER&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.1.Alıcı, www.saklicekmecem.com internet sitesinde s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n temel nitelikleri, t&amp;uuml;m vergiler dahil satış fiyatı ve &amp;ouml;deme şekli ile teslimata ve bunun masraflarının alıcı tarafından karşılanacağına, teslimatın ger&amp;ccedil;ekleştirileceği s&amp;uuml;reye ve satıcının tam ticari unvanı, a&amp;ccedil;ık adresi ve iletişim bilgilerine ilişkin &amp;ouml;n bilgileri okuyup bilgi sahibi olduğunu ve elektronik ortamda gerekli teyidi verdiğini beyan eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.2. Alıcı; bu s&amp;ouml;zleşmeyi elektronik ortamda teyit etmekle, mesafeli s&amp;ouml;zleşmelerin akdinden &amp;ouml;nce, satıcı tarafından t&amp;uuml;keticiye verilmesi gereken adres, siparişi verilen &amp;uuml;r&amp;uuml;nlere ait temel &amp;ouml;zellikler, &amp;uuml;r&amp;uuml;nlerin vergiler dahil fiyatı, &amp;ouml;deme ve teslimat bilgilerini de doğru ve eksiksiz olarak edindiğini teyid etmiş olur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.3. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n, yasal 30 g&amp;uuml;nl&amp;uuml;k s&amp;uuml;reyi aşmamak koşulu ile her bir &amp;uuml;r&amp;uuml;n i&amp;ccedil;in alıcının yerleşim yerinin uzaklığına bağlı olarak internet sitesinde &amp;ouml;n bilgiler i&amp;ccedil;inde a&amp;ccedil;ıklanan s&amp;uuml;re i&amp;ccedil;inde alıcı veya g&amp;ouml;sterdiği adresteki kişi/kuruluşa teslim edilir. Kargo ve Teslimat bilgileri kısmında g&amp;ouml;sterilen teslimata ilişkin her t&amp;uuml;rl&amp;uuml; kargo &amp;uuml;creti alıcı tarafından karşılanacak olup siparişine ilişkin faturasına &#39;&#39;Kargo &amp;Uuml;creti&#39;&#39; adı altında yansıtılacaktır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.4. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n, alıcıdan başka bir kişi/kuruluşa teslim edilecek ise, teslim edilecek kişi/kuruluşun teslimatı kabul etmemesinden satıcı sorumlu tutulamaz.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.5. Kargo firmasının, &amp;uuml;r&amp;uuml;n&amp;uuml; alıcıya teslimi aşamasında karşılaşacağı her t&amp;uuml;rl&amp;uuml; sorun nedeniyle, siparişi verilen &amp;uuml;r&amp;uuml;n&amp;uuml;n alıcıya teslim edilememesinden dolayı satıcı sorumlu tutulamaz.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.6. Satıcı, s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n sağlam, eksiksiz, siparişte belirtilen niteliklere uygun ve varsa garanti belgeleri ve kullanım kılavuzları ile teslim edilmesinden sorumludur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.7. Satıcı, haklı bir sebebe dayanmak şartıyla, s&amp;ouml;zleşmeden doğan ifa y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;n&amp;uuml;n s&amp;uuml;resi dolmadan alıcıya eşit kalite ve fiyatta farklı bir &amp;uuml;r&amp;uuml;n tedarik edebilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.8. Satıcı, sipariş konusu &amp;uuml;r&amp;uuml;n veya hizmetin yerine getirilmesinin imkansızlaşması halinde s&amp;ouml;zleşme konusu y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;klerini yerine getiremezse, bu durumu, s&amp;ouml;zleşmeden doğan ifa y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;n&amp;uuml;n s&amp;uuml;resi dolmadan t&amp;uuml;keticiye bildirir ve alıcıya eşit kalite ve fiyatta farklı bir &amp;uuml;r&amp;uuml;n tedarik edebilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.9. S&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n teslimatı i&amp;ccedil;in işbu s&amp;ouml;zleşmenin online ortamda kabul edilerek satıcıya ulaştırılmış olması ve bedelinin alıcının tercih ettiği &amp;ouml;deme şekli ile &amp;ouml;denmiş olması şarttır. Herhangi bir nedenle &amp;uuml;r&amp;uuml;n bedeli &amp;ouml;denmez veya banka kayıtlarında iptal edilir ise, satıcı &amp;uuml;r&amp;uuml;n&amp;uuml;n teslimi y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;nden kurtulmuş kabul edilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.10. &amp;Uuml;r&amp;uuml;n&amp;uuml;n tesliminden sonra alıcıya ait kredi kartının alıcının kusurundan kaynaklanmayan bir şekilde yetkisiz kişilerce haksız veya hukuka aykırı olarak kullanılması nedeni ile ilgili banka veya finans kuruluşun &amp;uuml;r&amp;uuml;n bedelini satıcıya &amp;ouml;dememesi halinde, alıcının kendisine teslim edilmiş olması kaydıyla &amp;uuml;r&amp;uuml;n&amp;uuml;n 3 g&amp;uuml;n i&amp;ccedil;inde satıcıya g&amp;ouml;nderilmesi zorunludur. Bu takdirde nakliye giderleri alıcıya aittir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;3.11. Satıcı m&amp;uuml;cbir sebepler veya nakliyeyi engelleyen hava muhalefeti, ulaşımın kesilmesi gibi olağan&amp;uuml;st&amp;uuml; durumlar nedeni ile s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml; s&amp;uuml;resi i&amp;ccedil;inde teslim edemez ise, durumu alıcıya bildirmekle y&amp;uuml;k&amp;uuml;ml&amp;uuml;d&amp;uuml;r. Bu takdirde alıcı siparişin iptal edilmesini, s&amp;ouml;zleşme konusu &amp;uuml;r&amp;uuml;n&amp;uuml;n varsa emsali ile değiştirilmesini, ve/veya teslimat s&amp;uuml;resinin engelleyici durumun ortadan kalkmasına kadar ertelenmesi haklarından birini kullanabilir. Alıcının siparişi iptal etmesi halinde &amp;ouml;dediği tutar 14 g&amp;uuml;n i&amp;ccedil;inde kendisine &amp;ouml;denir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcnın kredi kartı ile yaptığı &amp;ouml;demelerde ise, &amp;uuml;r&amp;uuml;n tutarı, siparişin alıcı tarafından iptal edilmesinden sonra 14 g&amp;uuml;n i&amp;ccedil;erisinde ilgili bankaya iade edilir. Bu tutarın bankaya iadesinden sonra alıcı hesaplarına yansıması tamamen banka işlem s&amp;uuml;reci ile ilgili olduğundan, alıcı, olası gecikmeler i&amp;ccedil;in satıcının herhangi bir şekilde m&amp;uuml;dahalede bulunmasının m&amp;uuml;mk&amp;uuml;n olamayacağını ve satıcı tarafından kredi kartına iade edilen tutarın banka tarafından alıcı hesabına yansıtılmasının ortalama 2 ile 3 haftayı bulabileceğini şimdiden kabul etmektedir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 4- TESLİMAT MASRAFLARI VE İFASI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Teslimat masrafları alıcıya aittir. Satıcı, web sitesinde, ilan ettiği rakamın &amp;uuml;zerinde alışveriş yapanların teslimat &amp;uuml;cretinin kendisince karşılanacağını beyan ettiği durumlarda, teslimat masrafı satıcıya aittir. Teslimat; stokun m&amp;uuml;sait olması ve mal bedelinin satıcının hesabına ge&amp;ccedil;mesinden sonra en kısa s&amp;uuml;rede yapılır. Satıcı, mal/hizmetin siparişinden itibaren 30 (Otuz) g&amp;uuml;n i&amp;ccedil;erisinde teslim eder. Herhangi bir nedenle mal/hizmet bedeli &amp;ouml;denmez veya banka kayıtlarında iptal edilir ise, Satıcı mal/hizmetin teslimi y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;ğ&amp;uuml;nden kurtulmuş kabul edilir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 5- S&amp;Ouml;ZLEŞMEYE KONU MAL/HİZMETİN &amp;Ouml;ZELLİKLERİ&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin cinsi ve t&amp;uuml;r&amp;uuml;, miktarı, marka/modeli, rengi ve t&amp;uuml;m vergiler d&amp;acirc;hil satış bedeli www.saklicekmecem.com adlı web sitesindeki mal/hizmet tanıtım sayfasında yer alan bilgilerde ve iş bu s&amp;ouml;zleşmenin ayrılmaz par&amp;ccedil;ası sayılan faturada belirtildiği gibidir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 6- MAL/HİZMETİN PEŞİN FİYATI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin peşin fiyatı sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 7- VADELİ FİYAT&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin satış fiyatına yapılan vadeye g&amp;ouml;re fiyatı&amp;nbsp;sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 8- FAİZ&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Mal/hizmetin satış fiyatına yapılan vadeye g&amp;ouml;re fiyatı&amp;nbsp;sipariş sonucu d&amp;uuml;zenlenen Mesafeli Satış S&amp;ouml;zleşmesinde belirtilen fatura &amp;ouml;zeti ve &amp;uuml;r&amp;uuml;n ile birlikte m&amp;uuml;şteriye g&amp;ouml;nderilen fatura i&amp;ccedil;eriğinde mevcuttur.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 9- CAYMA HAKKI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcı, s&amp;ouml;zleşme konusu mal/hizmetin kendisine veya g&amp;ouml;sterdiği adresteki kişi/kuruluşa tesliminden itibaren 14(ond&amp;ouml;rt) g&amp;uuml;n i&amp;ccedil;inde cayma hakkını kullanabilir. Cayma hakkının kullanılması i&amp;ccedil;in aynı s&amp;uuml;re i&amp;ccedil;inde satıcıya e-posta ile bildirimde bulunulması ve mal/hizmetin 15. md. h&amp;uuml;k&amp;uuml;mleri &amp;ccedil;er&amp;ccedil;evesinde ve işbu s&amp;ouml;zleşmenin ayrılmaz par&amp;ccedil;ası olan ve www.saklicekmecem.com web sitesinde yayınlanmış olan &amp;ouml;n bilgiler gereğince, kullanılmamış ve paketinin hasar g&amp;ouml;rmemiş ayrıca i&amp;ccedil; giyim &amp;uuml;r&amp;uuml;nlerinde ambalajının a&amp;ccedil;ılmamış olması şarttır. Bu hakkın kullanılması halinde, 3. kişiye veya alıcıya teslim edilen mal/hizmete ilişkin fatura aslının iadesi zorunludur. Cayma hakkına ilişkin ihbarın ulaşmasını takip eden 14 g&amp;uuml;n i&amp;ccedil;inde mal/hizmet bedeli alıcıya iade edilir ve 20 (yirmi) g&amp;uuml;nl&amp;uuml;k s&amp;uuml;re i&amp;ccedil;inde mal/hizmet iade alınır. Fatura aslı g&amp;ouml;nderilmezse alıcıya KDV ve varsa diğer yasal y&amp;uuml;k&amp;uuml;ml&amp;uuml;l&amp;uuml;kler iade edilemez. Cayma hakkı nedeni ile iade edilen mal/hizmetin teslimat bedeli satıcı tarafından karşılanır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 10- CAYMA HAKKI KULLANILAMAYACAK MAL/HİZMETLER&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Niteliği itibarıyla iade edilemeyecek mal/hizmetler, hızla bozulan ve son kullanma tarihi ge&amp;ccedil;en mal/hizmetler, tek kullanımlık mal/hizmetler, hijyen kuralları gerektiren &amp;uuml;r&amp;uuml;nlerdir. Ayrıca, her t&amp;uuml;rl&amp;uuml; giyim, sağlık ve kozmetik malzemelerinde cayma hakkının kullanılabilmesi i&amp;ccedil;in mal/hizmetin ambalajının a&amp;ccedil;ılmamış, bozulmamış ve kullanılmamış olmaları şartı bulunmaktadır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Teslimatta &amp;Ouml;deme metoduyla yapılan alış verişlerde, sipariş kargoya verildikten sonra cayma hakkı kullanılması durumunda, satıcının web sitesinde beyan ettiği miktarlardaki gidiş-d&amp;ouml;n&amp;uuml;ş kargo masrafları ile gidiş-d&amp;ouml;n&amp;uuml;ş tahsilatlı g&amp;ouml;nderi komisyon masrafları alıcı tarafından karşılanır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 11- TEMERR&amp;Uuml;D HALİ VE HUKUKİ SONU&amp;Ccedil;LARI&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Alıcı kredi kartı ile yapmış olduğu işlemlerinde temerr&amp;uuml;de d&amp;uuml;şmesi halinde kart sahibi bankanın kendisi ile yapmış olduğu kredi kartı s&amp;ouml;zleşmesi &amp;ccedil;er&amp;ccedil;evesinde faiz &amp;ouml;deyecek ve bankaya karsı sorumlu olacaktır. Bu durumda ilgili banka hukuki yollara başvurabilir; doğacak masrafları ve vek&amp;acirc;let &amp;uuml;cretini Alıcıdan talep edebilir ve her koşulda alıcının borcundan dolayı temerr&amp;uuml;de d&amp;uuml;şmesi halinde, alıcı, borcun gecikmeli ifasından dolayı satıcının oluşan zarar ve ziyanını &amp;ouml;demeyi kabul eder.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;MADDE 12-&amp;nbsp;YETKİLİ MAHKEME&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;İşbu s&amp;ouml;zleşmeden kaynaklanabilecek ihtilaflarda, Sanayi ve Ticaret Bakanlığınca ilan edilen değere kadar T&amp;uuml;ketici Hakem Heyetleri t&amp;uuml;ketici mahkemesi bulunamayan yerlerde Asliye Hukuk Mahkemeleri yetkilidir.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Siparişin ger&amp;ccedil;ekleşmesi durumunda ALICI işbu s&amp;ouml;zleşmenin t&amp;uuml;m koşullarını kabul etmiş sayılır.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;SATICI/SAĞLAYICI :&amp;nbsp;Safir Bitkisel &amp;Uuml;r&amp;uuml;nler Kırtasiye Giyim Temizlik REklam ve Organizasyon Sanayi ve Ticaret Limited Şirketi&lt;br /&gt;ALICI :&amp;nbsp;{%ALICI_ADISOYAD%}&lt;/p&gt;
";

?>