<?php if( !defined("SABIT") ){ exit; }
$footeryazi["tr"] = "&lt;div class=&quot;our-features-box&quot;&gt;
    &lt;div class=&quot;container&quot;&gt;
      &lt;ul&gt;
        &lt;li&gt;
          &lt;div class=&quot;feature-box need-help&quot;&gt;
            &lt;div class=&quot;icon-truck&quot;&gt;&lt;/div&gt;
            &lt;div class=&quot;content&quot;&gt;50 TL üstü Ücretsiz Kargo&lt;/div&gt;
          &lt;/div&gt;
        &lt;/li&gt;
        &lt;li&gt;
          &lt;div class=&quot;feature-box free-shipping&quot;&gt;
            &lt;div class=&quot;icon-support&quot;&gt;&lt;/div&gt;
            &lt;div class=&quot;content&quot;&gt;7/24 Müşteri Hizmetleri&lt;/div&gt;
          &lt;/div&gt;
        &lt;/li&gt;
        &lt;li&gt;
          &lt;div class=&quot;feature-box money-back&quot;&gt;
            &lt;div class=&quot;icon-money&quot;&gt;&lt;/div&gt;
            &lt;div class=&quot;content&quot;&gt;Sorgusuz Para İade Garantili&lt;/div&gt;
          &lt;/div&gt;
        &lt;/li&gt;
        &lt;li class=&quot;last&quot;&gt;
          &lt;div class=&quot;feature-box return-policy&quot;&gt;
            &lt;div class=&quot;icon-return&quot;&gt;&lt;/div&gt;
            &lt;div class=&quot;content&quot;&gt;30 gün Boyunca Destek&lt;/div&gt;
          &lt;/div&gt;
        &lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
  &lt;/div&gt;";
$kbaslik["tr"] = "HerbaTurk® Nedir?";
$anabaslik1["tr"] = "Sağlıklı Yaşam Ortağı®";
$anabaslik2["tr"] = "&lt;li id=&quot;menu-item-922&quot; class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-922&quot;&gt; &lt;a href=&quot;index.php&quot;&gt;Online Kataloglar &lt;i class=&quot;icon-book-open&quot;&gt;&lt;/i&gt;&lt;/a&gt;&lt;/li&gt;";
$anabaslik3["tr"] = "&lt;p&gt;Tel: 000 000 000 000&lt;/p&gt;
&lt;p&gt;Tel: 000 000 000 000&lt;/p&gt;
&lt;p&gt;Tel: 000 000 000 000&lt;/p&gt;
&lt;p&gt;Tel: 000 000 000 000&lt;/p&gt;
&lt;p&gt;Tel: 000 000 000 000&lt;/p&gt;";
$anabaslik4["tr"] = "Türkiyenin Lider Çiçekci E-Satış Sitesi";
$anabaslik5["tr"] = "0212 212 2 212";
$anabaslik6["tr"] = "Tüm Ürünlerde 25% İndirim!";
$anabaslik7["tr"] = "Herkezden Önce Sende!";
$anabaslik8["tr"] = "İndirimli Ürünleri Kaçırma!";
$anabaslik9["tr"] = "Online Kataloglar";
$anabaslik10["tr"] = "Satış Noktaları";
$anabaslik11["tr"] = "Rende Medya Slogan Rende Medya Slogan  Rende Medya Slogan  Rende Medya Slogan";
$anabaslik12["tr"] = "*26.01.2017 tarih ve 29960 sayılı mükerrer Resmi Gazete&#39;de yayımlanan Türk Gıda Kodeksi Beslenme ve Sağlık Beyanları Yönetmeliği &lt;br/&gt;&lt;b&gt;“Dengeli ve çeşitli beslenme sağlıklı yaşam için önemlidir.”&lt;/b&gt;";
$anabaslik13["tr"] = "© 2018 Demoincele.com Tüm Hakkı Saklıdır.";
$ktext["tr"] = "&lt;hr /&gt;
&lt;p&gt;Voonka olarak, 2012 yılında, insanlara daha sağlıklı ve daha doğal bir yaşam sağlamak amacıyla yola &amp;ccedil;ıktık. Doğadan aldığımız ilhamla t&amp;uuml;keticilerimiz i&amp;ccedil;in sağlıklı &amp;ccedil;&amp;ouml;z&amp;uuml;mler sunmayı hedefliyoruz. Doğanın bize sunduklarını gelecek kuşaklara taşıyor ve bu ilhamla yarattığımız besin takviyelerini ihtiyacı olanlarla buluşturuyoruz.&lt;br /&gt;&lt;br /&gt;Kendimizi, hizmet ettiğimiz kişilerin&amp;nbsp;&lt;strong&gt;&amp;ldquo;Sağlıklı Yaşam Ortakları&amp;rdquo;&lt;/strong&gt;&amp;nbsp;olarak g&amp;ouml;r&amp;uuml;yor ve bu sorumluluk bilinci ile &amp;ccedil;alışıyoruz. Doğaya ve doğal kaynaklara duyduğumuz saygı ile hareket ediyor, d&amp;uuml;nyanın c&amp;ouml;mert&amp;ccedil;e sunduğu kaynaklardan gelecek kuşakların da rahat&amp;ccedil;a faydalanabilmesini ama&amp;ccedil;lıyoruz. Bu nedenle her faaliyetimizde &amp;ccedil;evre bilinci taşıyoruz...&amp;nbsp;&lt;/p&gt;";
$vtext["tr"] = "Tavsiye edilen günlük porsiyonu aşmayın. Takviye edici gıdalar normal beslenmenin yerine geçemez. Çocukların ulaşamayacağı yerde saklayın. Voonka ürünleri &lt;b&gt;
ilaç değildir&lt;/b&gt;
 Hastalıkların önlenmesi veya tedavi edilmesi amacıyla kullanılmaz. Hamilelik ve emzirme dönemi ile hastalık veya ilaç kullanılması durumlarında doktorunuza danışın.";
$vlink = "https://www.youtube.com/watch?v=KGI1jfax9cc";
$klink = "http://localhost/tr/sayfa/vizyonumuz-12";

?>